### ISSUE TITLE
ERROR:  type varchar2 does not exist

### ISSUE THREAD

**Issue by darold** [okbob/orafce_mail#4]
Hi Pavel,

I have seen this error now using latest versions of PG and orafce + orafce_mail when I try to restore a dump.
```
gilles=# create extension orafce;
CREATE EXTENSION
gilles=# create extension orafce_mail;
ERROR:  type varchar2 does not exist
```
Even if I set the default search_path on this database using the oracle schema first, the error appears.

The only thing that fix that is the VI command `:%s/ varchar2/ oracle.varchar2/` or if you prefer a call to `SET search_path TO oracle,public;` at start of the SQL script.

Kind regards,

**Comment by okbob** [comment]
Hi


so 24. 9. 2022 v 16:17 odesílatel Gilles Darold ***@***.***>
napsal:

> Hi Pavel,
>
> I have seen this error now using latest versions of PG and orafce +
> orafce_mail when I try to restore a dump.
>
> gilles=# create extension orafce;
> CREATE EXTENSION
> gilles=# create extension orafce_mail;
> ERROR:  type varchar2 does not exist
>
> Even if I set the default search_path on this database using the oracle
> schema first, the error appears.
>
> The only thing that fix that is the VI command :%s/ varchar2/
> oracle.varchar2/ or if you prefer a call to SET search_path TO
> oracle,public; at start of the SQL script.
>
> Kind regards,
>

Yes, I forgot to change this code. Will fix it. Thank you for echo

Regards

Pavel

**Comment by okbob** [comment]
ne 25. 9. 2022 v 8:26 odesílatel Pavel Stehule ***@***.***>
napsal:

> Hi
>
>
> so 24. 9. 2022 v 16:17 odesílatel Gilles Darold ***@***.***>
> napsal:
>
>> Hi Pavel,
>>
>> I have seen this error now using latest versions of PG and orafce +
>> orafce_mail when I try to restore a dump.
>>
>> gilles=# create extension orafce;
>> CREATE EXTENSION
>> gilles=# create extension orafce_mail;
>> ERROR:  type varchar2 does not exist
>>
>> Even if I set the default search_path on this database using the oracle
>> schema first, the error appears.
>>
>> The only thing that fix that is the VI command :%s/ varchar2/
>> oracle.varchar2/ or if you prefer a call to SET search_path TO
>> oracle,public; at start of the SQL script.
>>
>> Kind regards,
>>
>
> Yes, I forgot to change this code. Will fix it. Thank you for echo
>

It should be fixed now.

Please check
https://github.com/orafce/orafce_mail/releases/tag/VERSION_1_1_0

Attention. I moved this project to orafce folder

https://github.com/orafce/orafce_mail

There can be little bit more visible than in my private folder

Regards

Pavel

**Comment by darold** [comment]
Right it is solved, the only thing is that the Makefile must be fixed too with `DATA = orafce_mail--1.1.sql`

**Comment by okbob** [comment]
ne 25. 9. 2022 v 11:17 odesílatel Gilles Darold ***@***.***>
napsal:

> Right it is solved, the only thing is that the Makefile must be fixed too
> with DATA = orafce_mail--1.1.sql
>
My stupid mistake

should be fixed now

https://github.com/orafce/orafce_mail/releases/tag/VERSION_1_1_1

**Comment by darold** [comment]
Thanks Pavel.
